spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://10.0.0.136:3306/greeting
spring.datasource.username=greet
spring.datasource.password=J.YqwX83zz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
